config/routes.rb
Rails.application.routes.draw do
  get 'omniauth_callbacks/twitter'
  get 'passwords/edit'
  get 'sessions/new'
  #get 'main/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   root to: "main#index"

   get "sign_up", to: "registrations#new"
   post "sign_up", to: "registrations#create"

   get "sign_in", to: "sessions#new"
   post "sign_in", to: "sessions#create"
   delete "logout", to: "sessions#destroy"
  

   get "edit_password", to: "passwords#edit"
   patch "edit_password", to: "passwords#update"

   get "password/reset", to: "password_resets#new"
   post "password/reset", to: "password_resets#create"

   get "password/reset/edit", to: "password_resets#edit"
   patch "password/reset/edit", to: "password_resets#update"

   get "/auth/twitter/callback", to: "omniauth_callbacks#twitter"

   resources :twitter_accounts
   resources :tweets
   

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 24.hours.from_now
  end

  after_save_commit do
    if publish_at_previously_changed?
      TweetJob.set(wait_until: publish_at).perform_later(self)
    end
  end

  def published?
    tweet_id?
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  has_many :tweets , dependent: :destroy
  belongs_to :user

  validates :username, uniqueness: true

  def client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.credentials.dig(:twitter, :api_key)
      config.consumer_secret     = Rails.application.credentials.dig(:twitter, :api_secret_key)
      config.access_token        = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
    has_many :twitter_accounts
    has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil?
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!

  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password updated!"
    else
      render :edit
    end
  end


  private
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          redirect_to root_path, notice: "Successfully created account"
        else
          render :new
        end
      end
    
      private
    
      def user_params
        # Only this params are permited so user cant set up admin flag to be true
        params.require(:user).permit(:email, :password, :password_confirmation)
      end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :require_user_logged_in!
    before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  
    def index
      @tweets = Current.user.tweets
    end
  
    def new
      @tweet = Tweet.new
    end
  
    def create
      @tweet = Current.user.tweets.new(tweet_params)
      if @tweet.save
        redirect_to tweets_path, notice: "Tweet was scheduled successfully"
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @tweet.update(tweet_params)
        redirect_to tweets_path, notice: "Tweet was updated successfully"
      else
        render :edit
      end
    end
  
    def destroy
      @tweet.destroy
      redirect_to tweets_path, notice: "Tweet was unscheduled"
    end
  
    private
  
    def tweet_params
      params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
    end
  
    def set_tweet
      @tweet = Current.user.tweets.find(params[:id])
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/twitter_accounts_helper.rb
module TwitterAccountsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buffer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <%= render partial: "shared/flash" %>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
  <div class="alert alert-danger">
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Tweets", tweets_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Twitter Accounts", twitter_accounts_path, class: "nav-link" %>
        </li>
        
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
        <li class="nav-item">
          <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", sign_in_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>